name: api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  dart_frog_web_socket: ^1.0.0
  envied: ^0.5.3
  google_generative_ai: ^0.2.0  
  models:
    path: ../packages/models
  uuid: ^4.3.3
 
dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  mocktail: ^1.0.0
  test: ^1.19.2
